---
# The following with update the Local Repositories for OracleLinux and Ubuntu Servers
- hosts: all
  become: true
  tasks:

  - name: Install updates (OracleLinux)
    dnf:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "OracleLinux"  


  - name: Install updates (OracleLinux)
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"  



# Plays for web servers

- hosts: web_servers
  become: true
  tasks:

# The following are installation for Ubuntu
  - name: Update Repo Index, Install Apache, php support and telnet
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
    when:
      - ansible_distribution == "Ubuntu"


# The following are installation for Oracle Linux
  - name: Install Apache, php support and telnet For Oracle Linux
    dnf:
      name:
        - httpd
        - php
        - telnet
      state: latest
    when:
      - ansible_distribution == "OracleLinux"  





# Plays for db servers

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB (OracleLinux)
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "OracleLinux"  

  - name: Install MariaDB (Ubuntu)
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"  




# Plays for file servers

- hosts: file_servers
  become: true
  tasks:

  - name: Install Samba (OracleLinux, Ubuntu)
    package:
      name:
        - samba
      state: latest

  - name: Install NFS SERVER (OracleLinux)
    dnf:
      name:
        - nfs-utils
      state: latest
    when: ansible_distribution == "OracleLinux"  

  - name: Install NFS SERVER (Ubuntu)
    apt:
      name:
        - nfs-kernel-server
      state: latest
    when: ansible_distribution == "Ubuntu"  
