---

- hosts: all
  become: true
  tasks:

# The following are installation for Ubuntu
  - name: Update Repo Index, Install Apache, php support and htop
    apt:
      update_cache: yes 
      name:
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
    when:
      - ansible_distribution == "Ubuntu"


# The following are installation for OracleLinux
  - name: Install Apache, php support and htop For Oracle Linux
    dnf:
      update_cache: yes 
      name:
        - httpd
        - php
        - htop
      state: latest
    when:
      - ansible_distribution == "OracleLinux"  
