---

- hosts: all
  become: true
  tasks:

  - name: Update Repo Index, Install Apache, php support and htop
      update_cache: yes 
    apt:
      update_cache: yes 
      name:
        - apache2
        - libapache2-mod-php
        - htop
      state: latest
    when:
      - ansible_distribution == "Ubuntu"

  - name: Install Apache, php support and htop For Oracle Linux
    dnf:
      update_cache: yes 
      name:
        - httpd
        - php
        - htop
      state: latest
    when:
      - ansible_distribution == "OracleLinux"  
