---
# The following with update the Local Repositories for OracleLinux and Ubuntu Servers
- hosts: all
  become: true
  roles:
    - base 

 
# Plays for web servers

- hosts: web_servers
  become: true
  roles:
    - web_servers

# Plays for db servers

- hosts: db_servers
  become: true
  roles:
    - db_servers
      

# Plays for file servers

- hosts: file_servers
  become: true
  roles:
    - file_servers
