---
# The following with update the Local Repositories for OracleLinux and Ubuntu Servers
- hosts: all
  become: true
  tasks:

  - name: Install updates (OracleLinux)
    tags: update,oracleLinux
    dnf:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "OracleLinux"  


  - name: Install updates (OracleLinux)
    tags: update,ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"  

  - name: Create oga user
    tags: always,user
    user:
      name: oga
      groups: root
      shell: /bin/bash

  - name: Create test user
    tags: always,user
    user:
      name: test2
      groups: root
      shell: /bin/bash


  - name: Add ssh keys for oga user
    tags: always
    authorized_key:
      user: oga
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILaBU7Fk2Q1dRj3IgqA+rc2eRxdKdr3nbXVUtSq/my9/ ingryd-ansible-project"
  
  - name: Add oga to sudoers file
    tags: always
    copy:
      src: sudoer_oga
      dest: /etc/sudoers.d/oga
      owner: root
      group: root
      mode: 0440


# Plays for web servers

- hosts: web_servers
  become: true
  tasks:

# The following are installation for Ubuntu
  - name: Update Repo Index, Install Apache, php support and telnet
    tags: apache2,web_server,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
        - telnet
      state: latest
    when:
      - ansible_distribution == "Ubuntu"


# The following are installation for Oracle Linux
  - name: Install Apache, php support and telnet For Oracle Linux
    tags: httpd,web_server,oracleLinux
    dnf:
      name:
        - httpd
        - php
        - telnet
      state: latest
    when:
      - ansible_distribution == "OracleLinux"  

  - name: Copy Html file for site
    tags: apache2,httpd,copy
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: Start Httpd (OracleLinux)
    tags: apache2,httpd,oracleLinux
    when: ansible_distribution == "OracleLinux"
    service:
      name: httpd
      state: started
      enabled: yes

  - name: Change email address for admin (OracleLinux)
    tags: apache2,httpd,web_server,oracleLinux
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin chineduogada@gmail.com
    register: httpd
    when: ansible_distribution == "OracleLinux"


  - name: Restart Http (OracleLinux)
    tags: apache2,httpd,web_server,oracleLinux
    service:
      name: httpd
      state: restarted
    when: httpd.changed

# Plays for db servers

- hosts: db_servers
  become: true
  tasks:

  - name: Install MariaDB (OracleLinux)
    tags: mariadb,db_server,oracleLinux
    dnf:
      name:
        - mariadb
      state: latest
    when: ansible_distribution == "OracleLinux"  

  - name: Install MariaDB (Ubuntu)
    tags: mariadb,db_server,ubuntu
    apt:
      name:
        - mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"  




# Plays for file servers

- hosts: file_servers
  become: true
  tasks:

  - name: Install Samba (OracleLinux, Ubuntu)
    tags: oracleLinux,ubuntu,samba,file_server
    package:
      name:
        - samba
      state: latest

  - name: Install NFS SERVER (OracleLinux)
    tags: oracleLinux,nfs,file_server
    dnf:
      name:
        - nfs-utils
      state: latest
    when: ansible_distribution == "OracleLinux"  

  - name: Install NFS SERVER (Ubuntu)
    tags: ubuntu,nfs,file_server
    apt:
      name:
        - nfs-kernel-server
      state: latest
    when: ansible_distribution == "Ubuntu"  

  - name: Copy instruction manual to home dir (OracleLinux, Ubuntu)
    tags: copy,file_server,exercise2
    copy:
      src: instruction_manual.txt
      dest: /home/zero
      owner: zero
      group: zero
      mode: 0664

  - name: Install Unzip
    tags: copy,file_server
    package:
      name: unzip

  - name: Install OpenToFu
    unarchive:
      src: https://github.com/opentofu/opentofu/releases/download/v1.6.0-rc1/tofu_1.6.0-rc1_darwin_arm64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755
