---
# The following with update the Local Repositories for OracleLinux and Ubuntu Servers
- hosts: all
  become: true
  roles:
    - base 

# The below plays update all servers

- hosts: all
  become: true
  tasks:

  - name: Install updates (OracleLinux)
    tags: update,oracleLinux
    dnf:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "OracleLinux"  


  - name: Install updates (Ubuntu)
    tags: update,ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu" 
 
# Plays for web servers

- hosts: web_servers
  become: true
  roles:
    - web_servers

# Plays for db servers

- hosts: db_servers
  become: true
  roles:
    - db_servers
      

# Plays for file servers

- hosts: file_servers
  become: true
  roles:
    - file_servers

 

